_STATES =  {'Alabama' : 'AL',
'Alaska' : 'AK',
'Arizona' : 'AZ',
'Arkansas' : 'AR',
'California' : 'CA',
'Colorado' : 'CO',
'Connecticut' : 'CT',
'District of Columbia' : 'DC', 
'Delaware' : 'DE',
'Florida' : 'FL',
'Georgia' : 'GA',
'Hawaii' : 'HI',
'Idaho' : 'ID',
'Illinois' : 'IL',
'Indiana' : 'IN',
'Iowa' : 'IA',
'Kansas' : 'KS',
'Kentucky' : 'KY',
'Louisiana' : 'LA',
'Maine' : 'ME',
'Maryland' : 'MD',
'Massachusetts' : 'MA',
'Michigan' : 'MI',
'Minnesota' : 'MN',
'Mississippi' : 'MS',
'Missouri' : 'MO',
'Montana' : 'MT',
'Nebraska' : 'NE',
'Nevada' : 'NV',
'New Hampshire' : 'NH',
'New Jersey' : 'NJ',
'New Mexico' : 'NM',
'New York' : 'NY',
'North Carolina' : 'NC',
'North Dakota' : 'ND',
'Ohio' : 'OH',
'Oklahoma' : 'OK',
'Oregon' : 'OR',
'Pennsylvania' : 'PA',
'Rhode Island' : 'RI',
'South Carolina' : 'SC',
'South Dakota' : 'SD',
'Tennessee' : 'TN',
'Texas' : 'TX',
'Utah' : 'UT',
'Vermont' : 'VT',
'Virginia' : 'VA',
'Washington' : 'WA',
'West Virginia' : 'WV',
'Wisconsin' : 'WI',
'Wyoming' : 'WY'
}


_REGIONS = {'south_east' : ['Louisiana', 'Arkansas', 'Mississippi', 'Tennessee', 'Alabama', 
                           'Kentucky', 'Florida', 'Georgia', 'South Carolina', 'North Carolina', 
                           'Virginia', 'West Virginia','Delaware'],

           'north_east' : [ 'Maryland', 'New Jersey', 'New York','Connecticut', 'Rhode Island', 'Massachusetts', 
                           'New Hampshire', 'Maine', 'Vermont', 'Pennsylvania'],

           'mid_west' : ['North Dakota', 'South Dakota', 'Nebraska', 'Kansas', 'Minnesota', 'Missouri', 'Iowa',
                         'Wisconsin', 'Illinois', 'Indiana', 'Michigan', 'Ohio' ],

           'west_coast' : ['California', 'Alaska', 'Washington', 'Oregon', 'Nevada', 'Idaho', 'Utah', 'Montana', 
                           'Wyoming', 'Colorado', 'Hawaii'],
            
           'south_west' : ['Arizona', 'New Mexico', 'Texas', 'Oklahoma' ]
}